name: Helloworld workflow

on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: my code
        uses: actions/checkout@v2
      - name: Install Package
        run: pip install -t .
  test:
    runs-on: ubuntu-latest
      needs: build
      steps:
       - name: good bye
               
  


