name: File Handling

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello World"
        shell: bash
  create-file:
    runs-on: windows-latest
    steps:
      - name: Create Text File
        run: |
          echo "Hello, this is some text." > example.txt
        shell: bash

      - name: Display Contents
        run: cat example.txt
        shell: bash  
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read File
        run: |
          cat sample.txt
        shell: bash                

