name: Schedule Workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
    - cron: '*/8 * * * *'    # Runs every hour
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Repository Dispatch
      if: ${{ github.event_name == 'schedule' }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          "https://api.github.com/repos/skumarchirumamilla/myFirstRepo/dispatches" \
          -d '{"event_type": "hello_trigger"}'
    # New workflow for scheduling bye_trigger every hour
    - name: Trigger bye_trigger
      if: ${{ github.event_name == 'schedule' && contains(github.event.repository.full_name, 'schedule_bye_trigger') }}
      run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/skumarchirumamilla/myFirstRepo/dispatches" \
            -d '{"event_type": "bye_trigger"}'        

