name: Schedule Workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Repository Dispatch
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          "https://api.github.com/repos/skumarchirumamilla/myFirstRepo/dispatches" \
          -d '{"event_type": "hello_trigger"}'
